### ISSUE TITLE
Suggestion for autofarm

### ISSUE THREAD

**Issue by coreynj1** [CF-Trail/tzechco-PlsDonateAutofarmBackup#2]
Hello, I have a couple suggestions for features for the autofarm- 

A section where you can have automatic chat responses to certain things. If a player is near you, and says a specified thing, you automatically respond with a set list of responses similar to the other auto chat features. For example, if a player is near you and they say "hello", you automatically respond with "hello" back to seem more real.

When you join the server and first get a booth, it automatically moves you to a set position near the booth. I would love to have the ability to modify the position my character moves to. An easy way to do this would be to add a button that says "Update movement position for this booth". The player moves to the position they want the script to move to in the future, and they press the button. It records the position and angle of the player for that specific booth and saves it for next time.

Also, a way to prioritize which booth the script automatically chooses. Booth location matters and it should prefer booths closer to the shop, especially the two right next to the shop.

**Comment by CF-Trail** [comment]
will be added
![image](https://user-images.githubusercontent.com/106690765/210384300-73f6ced0-8104-49d6-82b8-b78a9bcdb36a.png)

??
![image](https://user-images.githubusercontent.com/106690765/210384346-77bfcc56-f131-46c6-988f-d400fba9f72f.png)

won't be added as im very lazy to rewrite booth code
![image](https://user-images.githubusercontent.com/106690765/210384366-5b8455c0-63b1-40df-ad27-2889eaff73ad.png)

**Comment by CF-Trail** [comment]
explain 2nd

**Comment by coreynj1** [comment]
Sure. When you first join the game, the script automatically walks you to a specified position near the booth you just claimed. I want to be able to change the position my character walks to and save it so it always walks to the new position I chose. I have a large avatar that mostly blocks the booth if I stand in front of it where the script normally has me stand, so I'd like to be able to stand above or to the sides of the booth.

**Comment by CF-Trail** [comment]
so you want to stand behind the booth, right?

**Comment by coreynj1** [comment]
Yes, or any other position near to the booth instead of in front of it where I'm completely blocking access to the gamepasses.

**Comment by CF-Trail** [comment]
Is theres any way i can contact you thru discord? shoot me at szze#6220
